### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by ghost** [raboof/ewd#15]
I like the idea, but how to use it? Where can I see the results? 
Thanks, Damian

**Comment by raboof** [comment]
Thanks!

The site is generated automatically based on the specs in `.travis.yml`, generating the site at https://raboof.github.io/ewd/ . Does that answer your question?

**Comment by ghost** [comment]
Yes, I was looking for it, but could not find it. Thanks a lot and keep up the good work!

**Comment by raboof** [comment]
Cool thanks :)
